import { describe, it, expect } from "vitest";
import { parseGcode } from "./gcode-parser";
import { SLICER_PROFILES } from "./slicer-profiles";

const PLA_DENSITY = 1.24;

// ─── Helper: Minimal G-code generators per slicer ───────

function makeAnkerGcode(layers = 3, gramsPerLayer = 10) {
  const extrusionPerLayer =
    (gramsPerLayer * 1000) / (Math.PI * (1.75 / 2) ** 2 * PLA_DENSITY);
  let gcode = `;Filament weight: ${(layers * gramsPerLayer).toFixed(1)}g\nM83\n`;
  for (let i = 0; i < layers; i++) {
    gcode += `;LAYER:${i}\nG1 X${10 + i * 10} Y10 E${extrusionPerLayer.toFixed(4)}\n`;
  }
  return gcode;
}

function makeCuraGcode(layers = 3, metersUsed = 1.2) {
  let gcode = `;Generated with Cura_SteamEngine 5.7.2\n;Filament used: ${metersUsed}m\nM83\n`;
  for (let i = 0; i < layers; i++) {
    gcode += `;LAYER:${i}\nG1 X${10 + i * 10} Y10 E5.0\n`;
  }
  return gcode;
}

function makePrusaGcode(layers = 3, gramsUsed = 30) {
  let gcode = `; generated by PrusaSlicer 2.7.1\n; filament used [g] = ${gramsUsed}\n; filament_density = ${PLA_DENSITY}\nM83\n`;
  for (let i = 0; i < layers; i++) {
    gcode += `;LAYER_CHANGE\n;HEIGHT:${(0.2 * (i + 1)).toFixed(2)}\nG1 X${10 + i * 10} Y10 E5.0\n`;
  }
  return gcode;
}

function makeSimplify3dGcode(layers = 3, weightGrams = 30) {
  let gcode = `; Generated with Simplify3D(R) Version 5.1.2\n;   Plastic weight: ${weightGrams.toFixed(2)} g\nM83\n`;
  for (let i = 0; i < layers; i++) {
    gcode += `; layer ${i + 1}, Z = ${(0.3 * (i + 1)).toFixed(2)}\nG1 X${10 + i * 10} Y10 E5.0\n`;
  }
  return gcode;
}

function makeBambuGcode(layers = 3, gramsUsed = 30) {
  let gcode = `; BambuStudio 02.00.01.50\n; total filament weight [g] = ${gramsUsed}\n; filament_density = ${PLA_DENSITY}\nM83\n`;
  for (let i = 0; i < layers; i++) {
    gcode += `; CHANGE_LAYER\nG1 X${10 + i * 10} Y10 E5.0\n`;
  }
  return gcode;
}

// ─── parseGcode — Success cases ─────────────────────────

describe("parseGcode", () => {
  describe("AnkerMake format", () => {
    it("parses layers correctly", () => {
      const result = parseGcode(makeAnkerGcode(5, 10), PLA_DENSITY);
      expect("type" in result).toBe(false);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(5);
      expect(result.headerGrams).toBeCloseTo(50, 0);
      expect(result.totalGrams).toBeCloseTo(50, 0);
    });

    it("uses header weight as authoritative", () => {
      const gcode = `;Filament weight: 100.0g\nM83\n;LAYER:0\nG1 X10 Y10 E50\n;LAYER:1\nG1 X20 Y20 E50\n`;
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      expect(result.headerGrams).toBe(100);
      expect(result.totalGrams).toBe(100);
    });
  });

  describe("Cura format", () => {
    it("detects Cura and parses ;LAYER:N markers", () => {
      const result = parseGcode(makeCuraGcode(4, 1.5), PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(4);
      expect(result.metadata.slicer.profile.id).toBe("cura");
    });

    it("converts meters to grams using density", () => {
      const result = parseGcode(makeCuraGcode(3, 2.0), PLA_DENSITY);
      if ("type" in result) return;
      // 2 meters = 2000mm → should yield reasonable grams
      expect(result.headerGrams).toBeGreaterThan(0);
    });
  });

  describe("PrusaSlicer format", () => {
    it("detects PrusaSlicer and parses ;LAYER_CHANGE markers", () => {
      const result = parseGcode(makePrusaGcode(6, 45), PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(6);
      expect(result.metadata.slicer.profile.id).toBe("prusaslicer");
      expect(result.headerGrams).toBe(45);
    });

    it("extracts density from header metadata", () => {
      const result = parseGcode(makePrusaGcode(3, 30), PLA_DENSITY);
      if ("type" in result) return;
      expect(result.metadata.density).toBe(PLA_DENSITY);
      expect(result.metadata.material).toBeNull(); // PrusaSlicer uses filament_type not in our fixture
    });
  });

  describe("Simplify3D format", () => {
    it("detects Simplify3D and parses ; layer N markers", () => {
      const result = parseGcode(makeSimplify3dGcode(4, 25), PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(4);
      expect(result.metadata.slicer.profile.id).toBe("simplify3d");
      expect(result.headerGrams).toBeCloseTo(25, 0);
    });
  });

  describe("BambuStudio format", () => {
    it("detects BambuStudio and parses ; CHANGE_LAYER markers", () => {
      const result = parseGcode(makeBambuGcode(5, 40), PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(5);
      expect(result.metadata.slicer.profile.id).toBe("bambustudio");
      expect(result.headerGrams).toBe(40);
    });
  });

  describe("Manual slicer override", () => {
    it("uses override profile instead of auto-detect", () => {
      // G-code with Cura header but force PrusaSlicer parsing
      const gcode = `;Generated with Cura_SteamEngine 5.7.2\nM83\n;LAYER_CHANGE\nG1 X10 Y10 E5\n;LAYER_CHANGE\nG1 X20 Y20 E5\n`;
      const result = parseGcode(gcode, PLA_DENSITY, {
        slicerOverride: SLICER_PROFILES.prusaslicer,
      });
      if ("type" in result) return;
      // Should find 2 layers using LAYER_CHANGE pattern
      expect(result.totalLayers).toBe(2);
    });
  });

  // ─── Extrusion mode handling ────────────────────────

  describe("extrusion modes", () => {
    it("handles relative extrusion (M83)", () => {
      const gcode = `;Filament weight: 10g\nM83\n;LAYER:0\nG1 X10 Y10 E300.0\nG1 X20 Y20 E400.0\n;LAYER:1\nG1 X30 Y30 E200.0\n`;
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(2);
      // Relative: layer 0 = 300+400=700mm, layer 1 = 200mm → significant grams
      expect(result.parsedGrams).toBeGreaterThan(0);
    });

    it("handles absolute extrusion (M82)", () => {
      const gcode = `;Filament weight: 10g\nM82\n;LAYER:0\nG1 X10 Y10 E300.0\nG1 X20 Y20 E700.0\n;LAYER:1\nG1 X30 Y30 E900.0\n`;
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(2);
      // Absolute: layer 0 = (700-0)=700mm, layer 1 = (900-700)=200mm
      expect(result.parsedGrams).toBeGreaterThan(0);
    });

    it("handles G92 E0 reset in absolute mode", () => {
      const gcode = `;Filament weight: 10g\nM82\n;LAYER:0\nG1 X10 Y10 E500.0\nG92 E0\n;LAYER:1\nG1 X20 Y20 E300.0\n`;
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(2);
      // After reset: layer 1 extrusion should be 300mm not (300-500) which would be negative
      expect(result.parsedGrams).toBeGreaterThan(0);
    });

    it("handles mixed modes (M82 then M83 mid-file)", () => {
      const gcode = `;Filament weight: 10g\nM82\n;LAYER:0\nG1 X10 Y10 E5.0\nM83\n;LAYER:1\nG1 X20 Y20 E3.0\nG1 X30 Y30 E2.0\n`;
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      expect(result.totalLayers).toBe(2);
    });
  });

  // ─── Retraction filtering ───────────────────────────

  describe("retraction filtering", () => {
    it("ignores retraction moves (E only, no XY)", () => {
      const gcode = `;Filament weight: 5g\nM83\n;LAYER:0\nG1 E-3 F3600\nG1 X10 Y10 E5.0\nG1 E3 F3600\n;LAYER:1\nG1 X20 Y20 E4.0\n`;
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      // Only the XY moves count: 5 + 4 = 9mm total
      // Retraction (-3) and unretraction (3) without XY are ignored
      expect(result.totalLayers).toBe(2);
    });
  });

  // ─── Error cases ────────────────────────────────────

  describe("error handling", () => {
    it("returns validation error for empty content", () => {
      const result = parseGcode("", PLA_DENSITY);
      expect("type" in result).toBe(true);
      if (!("type" in result)) return;
      expect(result.type).toBe("validation");
    });

    it("returns no_layers error when no layer markers found", () => {
      const gcode = "G28\nM83\nG1 X10 Y10 E5\nG1 X20 Y20 E5\n";
      const result = parseGcode(gcode, PLA_DENSITY);
      expect("type" in result).toBe(true);
      if (!("type" in result)) return;
      expect(result.type).toBe("no_layers");
    });

    it("returns no_extrusion error when layers exist but no E values", () => {
      const gcode =
        "G28\n;LAYER:0\nG1 X10 Y10 F1500\n;LAYER:1\nG1 X20 Y20 F1500\n";
      const result = parseGcode(gcode, PLA_DENSITY);
      expect("type" in result).toBe(true);
      if (!("type" in result)) return;
      expect(result.type).toBe("no_extrusion");
    });
  });

  // ─── Warnings ───────────────────────────────────────

  describe("warnings", () => {
    it("warns on low-confidence slicer detection", () => {
      const gcode =
        "G28\nM83\n;LAYER:0\nG1 X10 Y10 E5\n;LAYER:1\nG1 X20 Y20 E5\n";
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      // No header match → medium confidence (;LAYER:N heuristic) → no warning
      // But generic would warn
    });

    it("warns on header/parsed weight mismatch >5%", () => {
      // Header says 100g but actual extrusion is much less
      const gcode = `;Filament weight: 100.0g\nM83\n;LAYER:0\nG1 X10 Y10 E1.0\n`;
      const result = parseGcode(gcode, PLA_DENSITY);
      if ("type" in result) return;
      expect(result.warnings.some((w) => w.includes("differs"))).toBe(true);
    });
  });
});
