/**
 * Slicer profile definitions for multi-slicer G-code parsing.
 * Each profile defines how a specific slicer formats its G-code output,
 * enabling auto-detection and correct parsing of layer data.
 */

// ─── Types ──────────────────────────────────────────────

export type SlicerId =
  | "ankermaker"
  | "cura"
  | "prusaslicer"
  | "orcaslicer"
  | "bambustudio"
  | "simplify3d"
  | "superslicer"
  | "ideamaker"
  | "generic";

export interface WeightPattern {
  pattern: RegExp;
  unit: "grams" | "mm" | "meters" | "cm3";
}

export interface PauseInstruction {
  title: string;
  steps: string[];
  command: string; // M600, M0, or slicer-specific
  note?: string;
}

export interface SlicerProfile {
  id: SlicerId;
  name: string;
  // Detection — matched against first 150 lines
  headerPattern: RegExp;
  versionExtractor?: RegExp;

  // Parsing
  layerMarker: RegExp;
  weightPatterns: WeightPattern[];
  densityPattern?: RegExp;
  materialPattern?: RegExp;
  diameterPattern?: RegExp;
  colorPattern?: RegExp;

  // AMS / Multi-material
  isMultiMaterial: boolean;
  toolChangePattern?: RegExp;

  // UI — how to set up pauses in this slicer
  pauseInstructions: PauseInstruction;
}

// ─── Profiles ───────────────────────────────────────────

export const SLICER_PROFILES: Record<SlicerId, SlicerProfile> = {
  ankermaker: {
    id: "ankermaker",
    name: "AnkerMake / EufyMake Studio",
    headerPattern: /^;Filament weight:/im,
    layerMarker: /^;LAYER:\d+/i,
    weightPatterns: [
      { pattern: /^;Filament weight:\s*([\d.]+)\s*g/i, unit: "grams" },
    ],
    isMultiMaterial: false,
    pauseInstructions: {
      title: "Set Pause in EufyMake Studio",
      steps: [
        "Open EufyMake Studio and load your G-code",
        "In the preview, drag the layer slider on the right to layer {layer}",
        "Click the + button to add a pause marker",
        "The printer will pause BEFORE printing this layer",
      ],
      command: "EufyMake UI marker",
      note: "EufyMake pauses before printing the marked layer — set the marker on the first layer of the next spool.",
    },
  },

  cura: {
    id: "cura",
    name: "Cura / Creality Print",
    headerPattern: /^;Generated with Cura/im,
    versionExtractor: /^;Generated with Cura_SteamEngine\s+([\d.]+)/im,
    layerMarker: /^;LAYER:\d+/i,
    weightPatterns: [
      // Cura reports in meters by default: ";Filament used: 1.20047m"
      { pattern: /^;Filament used:\s*([\d.]+)m\s*$/im, unit: "meters" },
      // Some configs report mm: ";Filament used: 1200.47mm"
      { pattern: /^;Filament used:\s*([\d.]+)mm\s*$/im, unit: "mm" },
      // Custom weight comment if user added it
      { pattern: /^;Filament weight\s*=?\s*([\d.]+)\s*g/i, unit: "grams" },
    ],
    densityPattern: /^;filament_density\s*=\s*([\d.]+)/im,
    materialPattern: /^;MATERIAL:\s*(.+)/im,
    isMultiMaterial: false,
    pauseInstructions: {
      title: "Add Filament Change in Cura",
      steps: [
        "Open Cura and load your model",
        "Go to Extensions → Post Processing → Modify G-Code",
        "Click Add a script → Filament Change",
        "Set Layer to {layer}",
        "Click Close and re-slice",
      ],
      command: "M600",
      note: "Cura inserts M600 at the specified layer. Make sure your printer firmware supports M600.",
    },
  },

  prusaslicer: {
    id: "prusaslicer",
    name: "PrusaSlicer",
    headerPattern: /^; generated by PrusaSlicer/im,
    versionExtractor: /^; generated by PrusaSlicer\s+([\d.]+)/im,
    layerMarker: /^;LAYER_CHANGE/i,
    weightPatterns: [
      { pattern: /^; filament used \[g\]\s*=\s*([\d.]+)/im, unit: "grams" },
      { pattern: /^; filament used \[mm\]\s*=\s*([\d.]+)/im, unit: "mm" },
      { pattern: /^; total filament used \[g\]\s*=\s*([\d.]+)/im, unit: "grams" },
    ],
    densityPattern: /^; filament_density\s*=\s*([\d.]+)/im,
    materialPattern: /^; filament_type\s*=\s*(.+)/im,
    diameterPattern: /^; filament_diameter\s*=\s*([\d.]+)/im,
    colorPattern: /^; filament_colour\s*=\s*#?([0-9A-Fa-f]{6})/im,
    isMultiMaterial: false,
    pauseInstructions: {
      title: "Add Pause in PrusaSlicer",
      steps: [
        "In PrusaSlicer, switch to the Preview tab",
        "Right-click the layer bar at layer {layer}",
        "Select Add custom G-code",
        "Enter M600 and click OK",
        "Re-export G-code",
      ],
      command: "M600",
      note: "You can also use the orange + button on the layer slider for color changes.",
    },
  },

  orcaslicer: {
    id: "orcaslicer",
    name: "OrcaSlicer",
    headerPattern: /^; generated by OrcaSlicer/im,
    versionExtractor: /^; generated by OrcaSlicer\s+([\d.]+)/im,
    layerMarker: /^;LAYER_CHANGE/i,
    weightPatterns: [
      { pattern: /^; total filament weight \[g\]\s*=\s*([\d.]+)/im, unit: "grams" },
      { pattern: /^; filament used \[g\]\s*=\s*([\d.]+)/im, unit: "grams" },
      { pattern: /^; filament used \[mm\]\s*=\s*([\d.]+)/im, unit: "mm" },
    ],
    densityPattern: /^; filament_density\s*=\s*([\d.]+)/im,
    materialPattern: /^; filament_type\s*=\s*(.+)/im,
    diameterPattern: /^; filament_diameter\s*=\s*([\d.]+)/im,
    colorPattern: /^; filament_colour\s*=\s*#?([0-9A-Fa-f]{6})/im,
    isMultiMaterial: true,
    toolChangePattern: /^T(\d+)/,
    pauseInstructions: {
      title: "Add Pause in OrcaSlicer",
      steps: [
        "In OrcaSlicer, switch to the Preview tab",
        "Right-click the layer bar at layer {layer}",
        "Select Add custom G-code",
        "Enter M600 and click OK",
        "Re-export G-code",
      ],
      command: "M600",
      note: "If using Bambu Lab AMS, filament swaps are handled automatically — no manual pauses needed.",
    },
  },

  bambustudio: {
    id: "bambustudio",
    name: "Bambu Studio",
    headerPattern: /^; BambuStudio/im,
    versionExtractor: /^; BambuStudio\s+([\d.]+)/im,
    layerMarker: /^; CHANGE_LAYER/i,
    weightPatterns: [
      { pattern: /^; total filament weight \[g\]\s*=\s*([\d.]+)/im, unit: "grams" },
      { pattern: /^; filament used \[g\]\s*=\s*([\d.]+)/im, unit: "grams" },
      { pattern: /^; filament used \[mm\]\s*=\s*([\d.]+)/im, unit: "mm" },
    ],
    densityPattern: /^; filament_density\s*=\s*([\d.]+)/im,
    materialPattern: /^; filament_type\s*=\s*(.+)/im,
    diameterPattern: /^; filament_diameter\s*=\s*([\d.]+)/im,
    colorPattern: /^; filament_colour\s*=\s*#?([0-9A-Fa-f]{6})/im,
    isMultiMaterial: true,
    toolChangePattern: /^T(\d+)/,
    pauseInstructions: {
      title: "Add Pause in Bambu Studio",
      steps: [
        "In Bambu Studio, switch to the Preview tab",
        "Right-click the layer bar at layer {layer}",
        "Select Insert pause (M601)",
        "The printer will pause before this layer",
      ],
      command: "M601",
      note: "If using AMS, filament swaps happen automatically. Manual pauses are only needed for single-extruder spool swaps.",
    },
  },

  simplify3d: {
    id: "simplify3d",
    name: "Simplify3D",
    headerPattern: /^; Generated with Simplify3D/im,
    versionExtractor: /^; Generated with Simplify3D.*Version\s*([\d.]+)/im,
    // Simplify3D uses "; layer N, Z = X.XX"
    layerMarker: /^; layer \d+/i,
    weightPatterns: [
      // Simplify3D includes weight in build summary: ";   Plastic weight: 12.34 g"
      { pattern: /^;\s*Plastic weight:\s*([\d.]+)\s*g/im, unit: "grams" },
      // Length in mm
      { pattern: /^;\s*Filament length:\s*([\d.]+)\s*mm/im, unit: "mm" },
    ],
    isMultiMaterial: false,
    pauseInstructions: {
      title: "Add Pause in Simplify3D",
      steps: [
        "In Simplify3D, go to Edit Process Settings",
        "Under the Scripts tab, find Layer Change Script",
        "Add a conditional: if layer == {layer}, insert M600",
        "Alternatively, add a new process starting at layer {layer} with M600 in Starting Script",
      ],
      command: "M600",
      note: "Simplify3D v5+ supports the Scripts tab for per-layer commands.",
    },
  },

  superslicer: {
    id: "superslicer",
    name: "SuperSlicer",
    headerPattern: /^; generated by SuperSlicer/im,
    versionExtractor: /^; generated by SuperSlicer\s+([\d.]+)/im,
    layerMarker: /^;LAYER_CHANGE/i,
    weightPatterns: [
      { pattern: /^; filament used \[g\]\s*=\s*([\d.]+)/im, unit: "grams" },
      { pattern: /^; filament used \[mm\]\s*=\s*([\d.]+)/im, unit: "mm" },
    ],
    densityPattern: /^; filament_density\s*=\s*([\d.]+)/im,
    materialPattern: /^; filament_type\s*=\s*(.+)/im,
    diameterPattern: /^; filament_diameter\s*=\s*([\d.]+)/im,
    colorPattern: /^; filament_colour\s*=\s*#?([0-9A-Fa-f]{6})/im,
    isMultiMaterial: false,
    pauseInstructions: {
      title: "Add Pause in SuperSlicer",
      steps: [
        "In SuperSlicer, switch to the Preview tab",
        "Right-click the layer bar at layer {layer}",
        "Select Add custom G-code",
        "Enter M600 and click OK",
        "Re-export G-code",
      ],
      command: "M600",
    },
  },

  ideamaker: {
    id: "ideamaker",
    name: "IdeaMaker",
    headerPattern: /^;Sliced by ideaMaker/im,
    versionExtractor: /^;Sliced by ideaMaker\s+([\d.]+)/im,
    // IdeaMaker uses ;LAYER:N like Cura
    layerMarker: /^;LAYER:\d+/i,
    weightPatterns: [
      // IdeaMaker puts usage in the footer: ";Material#1 Used: 1234.5mm"
      { pattern: /^;Material#\d+ Used:\s*([\d.]+)mm/im, unit: "mm" },
      // Some versions include grams
      { pattern: /^;Material#\d+ Used:\s*([\d.]+)g/im, unit: "grams" },
    ],
    isMultiMaterial: false,
    pauseInstructions: {
      title: "Add Pause in IdeaMaker",
      steps: [
        "In IdeaMaker, slice your model first",
        "Go to Edit → Modify G-code for a specific layer",
        "Select layer {layer}",
        "Add M600 in the Before Layer field",
        "Re-export G-code",
      ],
      command: "M600",
    },
  },

  generic: {
    id: "generic",
    name: "Unknown Slicer",
    // Never matches via auto-detect — this is the fallback
    headerPattern: /(?!)/,
    // Try both common patterns
    layerMarker: /^;LAYER[_:]?\s*\d+|^; layer \d+/i,
    weightPatterns: [
      { pattern: /^;\s*filament\s*(?:used|weight)\s*(?:\[g\])?\s*[=:]\s*([\d.]+)\s*g?/im, unit: "grams" },
      { pattern: /^;\s*filament\s*(?:used|length)\s*(?:\[mm\])?\s*[=:]\s*([\d.]+)\s*mm?/im, unit: "mm" },
      { pattern: /^;\s*Filament used:\s*([\d.]+)m\s*$/im, unit: "meters" },
    ],
    densityPattern: /^;\s*filament_density\s*=\s*([\d.]+)/im,
    materialPattern: /^;\s*filament_type\s*=\s*(.+)/im,
    diameterPattern: /^;\s*filament_diameter\s*=\s*([\d.]+)/im,
    isMultiMaterial: false,
    toolChangePattern: /^T(\d+)/,
    pauseInstructions: {
      title: "Add Filament Change Pause",
      steps: [
        "Open your G-code file in a text editor",
        "Find the line just before layer {layer} begins",
        "Insert M600 (filament change) or M0 (pause) on a new line",
        "Save and send to your printer",
      ],
      command: "M600",
      note: "Make sure your printer firmware supports the M600 or M0 command. Marlin, Klipper, and RepRapFirmware all support M600.",
    },
  },
};

// ─── Detection ──────────────────────────────────────────

export interface DetectionResult {
  profile: SlicerProfile;
  version: string | null;
  confidence: "high" | "medium" | "low";
}

/**
 * Auto-detect the slicer that generated a G-code file by scanning
 * the first ~150 lines for known header signatures.
 */
export function detectSlicer(text: string): DetectionResult {
  // Only scan the first 150 lines for efficiency
  const headerLines = text.split("\n", 150).join("\n");

  // Check each profile in priority order (most specific first)
  const profileOrder: SlicerId[] = [
    "orcaslicer",    // check before bambustudio (Orca is a Bambu fork)
    "bambustudio",
    "prusaslicer",
    "superslicer",   // check before prusaslicer patterns overlap
    "simplify3d",
    "cura",
    "ideamaker",
    "ankermaker",    // last — its pattern is less specific
  ];

  for (const id of profileOrder) {
    const profile = SLICER_PROFILES[id];
    if (profile.headerPattern.test(headerLines)) {
      let version: string | null = null;
      if (profile.versionExtractor) {
        const match = headerLines.match(profile.versionExtractor);
        if (match) version = match[1];
      }
      return { profile, version, confidence: "high" };
    }
  }

  // Heuristic fallback: check for layer marker style
  if (/^;LAYER_CHANGE/im.test(headerLines)) {
    // Prusa-family style but no header match
    return { profile: SLICER_PROFILES.prusaslicer, version: null, confidence: "medium" };
  }
  if (/^;LAYER:\d+/im.test(text.split("\n", 500).join("\n"))) {
    // Cura-family style
    return { profile: SLICER_PROFILES.cura, version: null, confidence: "medium" };
  }
  if (/^; layer \d+/im.test(text.split("\n", 500).join("\n"))) {
    return { profile: SLICER_PROFILES.simplify3d, version: null, confidence: "medium" };
  }

  return { profile: SLICER_PROFILES.generic, version: null, confidence: "low" };
}

// ─── Metadata Extraction ────────────────────────────────

export interface GcodeMetadata {
  slicer: DetectionResult;
  density: number | null;
  material: string | null;
  diameter: number | null;
  color: string | null;
  toolChangeCount: number;
  isMultiMaterial: boolean;
}

/**
 * Extract all metadata from G-code header without full parsing.
 * Used for quick validation and UI feedback before running the full parser.
 */
export function extractMetadata(text: string): GcodeMetadata {
  const slicer = detectSlicer(text);
  const profile = slicer.profile;
  const headerText = text.split("\n", 300).join("\n");

  let density: number | null = null;
  let material: string | null = null;
  let diameter: number | null = null;
  let color: string | null = null;

  if (profile.densityPattern) {
    const m = headerText.match(profile.densityPattern);
    if (m) density = parseFloat(m[1]);
  }
  if (profile.materialPattern) {
    const m = headerText.match(profile.materialPattern);
    if (m) material = m[1].trim();
  }
  if (profile.diameterPattern) {
    const m = headerText.match(profile.diameterPattern);
    if (m) diameter = parseFloat(m[1]);
  }
  if (profile.colorPattern) {
    const m = headerText.match(profile.colorPattern);
    if (m) color = `#${m[1]}`;
  }

  // Count tool changes to detect AMS/multi-material
  let toolChangeCount = 0;
  if (profile.toolChangePattern) {
    const lines = text.split("\n");
    const seen = new Set<string>();
    for (const line of lines) {
      const m = line.match(profile.toolChangePattern);
      if (m && !seen.has(m[1])) {
        seen.add(m[1]);
        toolChangeCount++;
      }
    }
  }

  return {
    slicer,
    density,
    material,
    diameter,
    color,
    toolChangeCount,
    isMultiMaterial: toolChangeCount > 1,
  };
}

// ─── Validation Helpers ─────────────────────────────────

export interface ValidationResult {
  valid: boolean;
  error?: string;
  warning?: string;
}

/**
 * Validate that a file is parseable G-code before attempting full parse.
 */
export function validateGcodeFile(
  content: string,
  fileName: string,
): ValidationResult {
  // Empty file
  if (!content || content.trim().length === 0) {
    return { valid: false, error: "File is empty." };
  }

  // Binary detection — check first 512 bytes for non-printable chars
  const sample = content.slice(0, 512);
  const nonPrintable = sample.split("").filter(
    (c) => {
      const code = c.charCodeAt(0);
      return code < 9 || (code > 13 && code < 32 && code !== 27);
    },
  ).length;
  if (nonPrintable > 5) {
    const ext = fileName.split(".").pop()?.toLowerCase();
    if (ext === "3mf" || ext === "zip") {
      return {
        valid: false,
        error: "This is a .3mf file, not G-code. Export as G-code (.gcode) from your slicer first.",
      };
    }
    if (ext === "stl" || ext === "obj") {
      return {
        valid: false,
        error: `This is a .${ext} model file, not G-code. Slice it first in your slicer software.`,
      };
    }
    return {
      valid: false,
      error: "This file contains binary data and doesn't appear to be G-code.",
    };
  }

  // Check for at least some G-code commands
  const hasGcode = /^[GMT]\d+/m.test(content);
  if (!hasGcode) {
    return {
      valid: false,
      error: "No G-code commands found in this file. Make sure you're uploading a sliced .gcode file.",
    };
  }

  // File size warning
  if (content.length > 50 * 1024 * 1024) {
    return {
      valid: true,
      warning: "Large file detected (>50MB). Parsing may take several seconds.",
    };
  }

  return { valid: true };
}

// ─── Unit Conversion ────────────────────────────────────

/**
 * Convert filament measurement to grams based on unit.
 * @param value - the numeric value from the G-code comment
 * @param unit - what unit the value is in
 * @param density - material density in g/cm³
 * @param diameter - filament diameter in mm (default 1.75)
 */
export function convertToGrams(
  value: number,
  unit: "grams" | "mm" | "meters" | "cm3",
  density: number,
  diameter: number = 1.75,
): number {
  const area = Math.PI * (diameter / 2) ** 2; // mm²

  switch (unit) {
    case "grams":
      return value;
    case "mm":
      // length_mm × area_mm² = volume_mm³, ÷1000 for cm³, × density
      return (value * area * density) / 1000;
    case "meters":
      // meters → mm, then same as above
      return (value * 1000 * area * density) / 1000;
    case "cm3":
      // volume_cm³ × density
      return value * density;
  }
}
