import { describe, it, expect } from "vitest";
import { parseGcode } from "./gcode-parser";
import {
  detectSlicer,
  extractMetadata,
  validateGcodeFile,
} from "./slicer-profiles";

/**
 * Integration tests that exercise the full pipeline:
 * detect slicer → extract metadata → parse layers → produce results
 */

describe("full pipeline integration", () => {
  it("PrusaSlicer: detect → parse → results with metadata", () => {
    const gcode = [
      "; generated by PrusaSlicer 2.7.1+linux-x64",
      "; filament used [g] = 45.23",
      "; filament_density = 1.24",
      "; filament_type = PLA",
      "; filament_colour = #FF5733",
      "; filament_diameter = 1.75",
      "M83 ; use relative distances for extrusion",
      ";LAYER_CHANGE",
      ";HEIGHT:0.2",
      "G1 X50 Y50 E200 F1500",
      "G1 X100 Y50 E200",
      ";LAYER_CHANGE",
      ";HEIGHT:0.4",
      "G1 X50 Y100 E200",
      "G1 X100 Y100 E200",
      ";LAYER_CHANGE",
      ";HEIGHT:0.6",
      "G1 X50 Y50 E200",
    ].join("\n");

    const result = parseGcode(gcode, 1.24);
    if ("type" in result) {
      expect.fail(`Parse failed: ${result.message}`);
      return;
    }

    expect(result.metadata.slicer.profile.id).toBe("prusaslicer");
    expect(result.metadata.slicer.version).toBe("2.7.1");
    expect(result.metadata.density).toBe(1.24);
    expect(result.metadata.material).toBe("PLA");
    expect(result.metadata.color).toBe("#FF5733");
    expect(result.metadata.diameter).toBe(1.75);
    expect(result.totalLayers).toBe(3);
    expect(result.headerGrams).toBeCloseTo(45.23, 1);
    expect(result.totalGrams).toBeCloseTo(45.23, 1);
  });

  it("Cura: meters → grams conversion with density", () => {
    const gcode = [
      ";Generated with Cura_SteamEngine 5.7.2",
      ";FLAVOR:Marlin",
      ";Filament used: 2.5m",
      ";LAYER_HEIGHT:0.2",
      "M83",
      ";LAYER:0",
      "G1 X50 Y50 E500 F1500",
      ";LAYER:1",
      "G1 X100 Y100 E500",
      ";LAYER:2",
      "G1 X50 Y50 E500",
    ].join("\n");

    const result = parseGcode(gcode, 1.24);
    if ("type" in result) {
      expect.fail(`Parse failed: ${result.message}`);
      return;
    }

    expect(result.metadata.slicer.profile.id).toBe("cura");
    expect(result.totalLayers).toBe(3);
    // 2.5 meters = 2500mm → converted to grams with 1.24 density
    expect(result.headerGrams).toBeGreaterThan(5);
    expect(result.headerGrams).toBeLessThan(20);
  });

  it("unknown slicer with generic fallback still parses", () => {
    const gcode = [
      "; some custom slicer output",
      "G28",
      "M83",
      ";LAYER:0",
      "G1 X10 Y10 E100 F1500",
      ";LAYER:1",
      "G1 X20 Y20 E100",
      ";LAYER:2",
      "G1 X30 Y30 E100",
    ].join("\n");

    const result = parseGcode(gcode, 1.24);
    if ("type" in result) {
      expect.fail(`Parse failed: ${result.message}`);
      return;
    }

    // Should still detect layers via heuristic (;LAYER:N → cura-family medium confidence)
    expect(result.totalLayers).toBe(3);
    expect(result.parsedGrams).toBeGreaterThan(0);
  });

  it("multi-material AMS detection", () => {
    const gcode = [
      "; BambuStudio 02.00.01.50",
      "; total filament weight [g] = 80",
      "; filament_density = 1.24",
      "M83",
      "T0",
      "; CHANGE_LAYER",
      "G1 X50 Y50 E200 F1500",
      "T1",
      "; CHANGE_LAYER",
      "G1 X100 Y100 E200",
      "T2",
      "; CHANGE_LAYER",
      "G1 X50 Y100 E200",
    ].join("\n");

    const result = parseGcode(gcode, 1.24);
    if ("type" in result) {
      expect.fail(`Parse failed: ${result.message}`);
      return;
    }

    expect(result.metadata.isMultiMaterial).toBe(true);
    expect(result.metadata.toolChangeCount).toBe(3);
    expect(result.warnings.some((w) => w.includes("Multi-material"))).toBe(
      true,
    );
  });

  it("handles file with only G-code commands (no slicer metadata)", () => {
    const gcode = [
      "G28",
      "G1 Z5 F5000",
      "M83",
      ";LAYER:0",
      "G1 X10 Y10 E100 F1500",
      "G1 X50 Y10 E100",
      "G1 X50 Y50 E100",
      ";LAYER:1",
      "G1 X10 Y50 E100",
      "G1 X10 Y10 E100",
    ].join("\n");

    const result = parseGcode(gcode, 1.24);
    if ("type" in result) {
      expect.fail(`Parse failed: ${result.message}`);
      return;
    }

    expect(result.totalLayers).toBe(2);
    expect(result.headerGrams).toBeNull();
    expect(result.parsedGrams).toBeGreaterThan(0);
    // No header → totalGrams equals the raw parsed value (parsedGrams is rounded for display)
    expect(result.totalGrams).toBeCloseTo(result.parsedGrams, 0);
  });
});

describe("validation edge cases", () => {
  it("rejects file that looks like HTML", () => {
    const html = "<!DOCTYPE html><html><body>Not gcode</body></html>";
    const result = validateGcodeFile(html, "page.html");
    expect(result.valid).toBe(false);
  });

  it("accepts file with BOM marker", () => {
    const gcode = "\uFEFFG28\nG1 X10 Y10 E1\n";
    const result = validateGcodeFile(gcode, "test.gcode");
    expect(result.valid).toBe(true);
  });

  it("accepts file with Windows line endings", () => {
    const gcode = "G28\r\nG1 X10 Y10 E1\r\n;LAYER:0\r\nG1 X20 Y20 E5\r\n";
    const result = parseGcode(gcode, 1.24);
    if ("type" in result) {
      expect.fail(`Parse failed: ${result.message}`);
      return;
    }
    expect(result.totalLayers).toBe(1);
  });

  it("handles extremely long lines gracefully", () => {
    const longComment = `; ${"x".repeat(10000)}`;
    const gcode = `${longComment}\nG28\n;LAYER:0\nG1 X10 Y10 E100\n`;
    const result = parseGcode(gcode, 1.24);
    if ("type" in result) {
      expect.fail(`Parse failed: ${result.message}`);
      return;
    }
    expect(result.totalLayers).toBe(1);
  });
});

describe("slicer detection edge cases", () => {
  it("handles case variations in slicer headers", () => {
    // Some slicers output slightly different casing
    const gcode =
      "; GENERATED BY PRUSASLICER 2.7.1\n;LAYER_CHANGE\nG1 X10 Y10 E100\n";
    const detection = detectSlicer(gcode);
    // Should still detect via the /i flag
    expect(detection.profile.id).toBe("prusaslicer");
  });

  it("extracts metadata when slicer is detected", () => {
    const gcode =
      "; generated by PrusaSlicer 2.7.1\n; filament_density = 1.27\n; filament_type = PETG\n;LAYER_CHANGE\nG1 X10 Y10 E100\n";
    const meta = extractMetadata(gcode);
    expect(meta.density).toBe(1.27);
    expect(meta.material).toBe("PETG");
  });
});
