import { describe, it, expect } from "vitest";
import {
  detectSlicer,
  validateGcodeFile,
  convertToGrams,
  extractMetadata,
  SLICER_PROFILES,
} from "./slicer-profiles";

// ─── detectSlicer ───────────────────────────────────────

describe("detectSlicer", () => {
  it("detects AnkerMake from header", () => {
    const gcode = `;Filament weight: 158.933g\n;LAYER:0\nG1 X10 Y10 E1\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("ankermaker");
    expect(result.confidence).toBe("high");
  });

  it("detects Cura from header", () => {
    const gcode = `;Generated with Cura_SteamEngine 5.7.2\n;FLAVOR:Marlin\n;TIME:7036\n;Filament used: 1.20047m\n;LAYER:0\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("cura");
    expect(result.confidence).toBe("high");
    expect(result.version).toBe("5.7.2");
  });

  it("detects PrusaSlicer from header", () => {
    const gcode = `; generated by PrusaSlicer 2.7.1+linux\n; filament used [g] = 45.2\n;LAYER_CHANGE\nG1 X10 Y10 E1\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("prusaslicer");
    expect(result.confidence).toBe("high");
    expect(result.version).toBe("2.7.1");
  });

  it("detects OrcaSlicer from header", () => {
    const gcode = `; generated by OrcaSlicer 2.2.0\n; filament_density = 1.24\n; filament_type = PLA\n;LAYER_CHANGE\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("orcaslicer");
    expect(result.confidence).toBe("high");
    expect(result.version).toBe("2.2.0");
  });

  it("detects BambuStudio from header", () => {
    const gcode = `; BambuStudio 02.00.01.50\n; filament_density = 1.27\n; CHANGE_LAYER\nG1 X10 Y10 E1\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("bambustudio");
    expect(result.confidence).toBe("high");
  });

  it("detects Simplify3D from header", () => {
    const gcode = `; Generated with Simplify3D(R) Version 5.1.2\n;   Plastic weight: 12.34 g\n; layer 1, Z = 0.300\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("simplify3d");
    expect(result.confidence).toBe("high");
  });

  it("detects SuperSlicer from header", () => {
    const gcode = `; generated by SuperSlicer 2.5.59.12\n; filament used [g] = 22.0\n;LAYER_CHANGE\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("superslicer");
    expect(result.confidence).toBe("high");
  });

  it("detects IdeaMaker from header", () => {
    const gcode = `;Sliced by ideaMaker 4.3.0.6515, 2024-01-15\n;LAYER:0\nG1 X10 Y10 E1\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("ideamaker");
    expect(result.confidence).toBe("high");
  });

  it("falls back to heuristic for LAYER_CHANGE without header", () => {
    const gcode = `G28\nM83\n;LAYER_CHANGE\n;HEIGHT:0.2\nG1 X10 Y10 E1\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("prusaslicer");
    expect(result.confidence).toBe("medium");
  });

  it("falls back to heuristic for ;LAYER:N without header", () => {
    const gcode = `G28\nM83\nG1 Z0.3\n;LAYER:0\nG1 X10 Y10 E1\n;LAYER:1\nG1 X20 Y20 E2\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("cura");
    expect(result.confidence).toBe("medium");
  });

  it("returns generic with low confidence for unrecognized format", () => {
    const gcode = `G28\nM83\nG1 X10 Y10 Z0.3 E1 F1500\nG1 X20 Y20 E2\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("generic");
    expect(result.confidence).toBe("low");
  });

  it("prioritizes OrcaSlicer over BambuStudio (fork detection)", () => {
    // If both patterns could match, Orca should win since it's checked first
    const gcode = `; generated by OrcaSlicer 2.2.0\n; BambuStudio\n;LAYER_CHANGE\n`;
    const result = detectSlicer(gcode);
    expect(result.profile.id).toBe("orcaslicer");
  });
});

// ─── validateGcodeFile ──────────────────────────────────

describe("validateGcodeFile", () => {
  it("rejects empty files", () => {
    const result = validateGcodeFile("", "test.gcode");
    expect(result.valid).toBe(false);
    expect(result.error).toContain("empty");
  });

  it("rejects whitespace-only files", () => {
    const result = validateGcodeFile("   \n  \n  ", "test.gcode");
    expect(result.valid).toBe(false);
    expect(result.error).toContain("empty");
  });

  it("rejects .3mf binary files", () => {
    const binary = "\x50\x4B\x03\x04" + "\x00".repeat(100); // ZIP header
    const result = validateGcodeFile(binary, "model.3mf");
    expect(result.valid).toBe(false);
    expect(result.error).toContain(".3mf");
  });

  it("rejects .stl files with binary content", () => {
    const binary = "\x00\x01\x02\x03\x04\x05\x06\x07" + "\x00".repeat(100);
    const result = validateGcodeFile(binary, "part.stl");
    expect(result.valid).toBe(false);
    expect(result.error).toContain(".stl");
  });

  it("rejects files with no G-code commands", () => {
    const result = validateGcodeFile("; just comments\n; more comments\n", "test.gcode");
    expect(result.valid).toBe(false);
    expect(result.error).toContain("No G-code commands");
  });

  it("accepts valid G-code", () => {
    const gcode = "G28\nG1 X10 Y10 E1 F1500\n";
    const result = validateGcodeFile(gcode, "test.gcode");
    expect(result.valid).toBe(true);
    expect(result.error).toBeUndefined();
  });

  it("warns for large files", () => {
    const gcode = "G1 X10 Y10 E1\n".repeat(4_000_000); // >50MB
    const result = validateGcodeFile(gcode, "big.gcode");
    expect(result.valid).toBe(true);
    expect(result.warning).toContain("Large file");
  });
});

// ─── convertToGrams ─────────────────────────────────────

describe("convertToGrams", () => {
  const PLA_DENSITY = 1.24;
  const DIAMETER = 1.75;

  it("passes through grams unchanged", () => {
    expect(convertToGrams(100, "grams", PLA_DENSITY, DIAMETER)).toBe(100);
  });

  it("converts mm of filament to grams", () => {
    // 1000mm × π × (0.875)² mm² = 2405.28 mm³ → 2.40528 cm³ × 1.24 = 2.983g
    const result = convertToGrams(1000, "mm", PLA_DENSITY, DIAMETER);
    expect(result).toBeCloseTo(2.983, 1);
  });

  it("converts meters of filament to grams", () => {
    // 1 meter = 1000mm → same as 1000mm
    const fromMeters = convertToGrams(1, "meters", PLA_DENSITY, DIAMETER);
    const fromMm = convertToGrams(1000, "mm", PLA_DENSITY, DIAMETER);
    expect(fromMeters).toBeCloseTo(fromMm, 5);
  });

  it("converts cm3 volume to grams", () => {
    // 10 cm³ × 1.24 density = 12.4g
    expect(convertToGrams(10, "cm3", PLA_DENSITY, DIAMETER)).toBeCloseTo(12.4, 5);
  });

  it("handles different diameters", () => {
    const d175 = convertToGrams(1000, "mm", PLA_DENSITY, 1.75);
    const d285 = convertToGrams(1000, "mm", PLA_DENSITY, 2.85);
    // 2.85mm diameter should give more volume per mm length
    expect(d285).toBeGreaterThan(d175);
    expect(d285 / d175).toBeCloseTo((2.85 / 1.75) ** 2, 1);
  });

  it("handles zero value", () => {
    expect(convertToGrams(0, "mm", PLA_DENSITY, DIAMETER)).toBe(0);
    expect(convertToGrams(0, "meters", PLA_DENSITY, DIAMETER)).toBe(0);
    expect(convertToGrams(0, "grams", PLA_DENSITY, DIAMETER)).toBe(0);
  });
});

// ─── extractMetadata ────────────────────────────────────

describe("extractMetadata", () => {
  it("extracts density from PrusaSlicer G-code", () => {
    const gcode = `; generated by PrusaSlicer 2.7.1\n; filament_density = 1.27\n; filament_type = PETG\n;LAYER_CHANGE\nG1 X10 Y10 E1\n`;
    const meta = extractMetadata(gcode);
    expect(meta.density).toBe(1.27);
    expect(meta.material).toBe("PETG");
    expect(meta.slicer.profile.id).toBe("prusaslicer");
  });

  it("extracts color from OrcaSlicer G-code", () => {
    const gcode = `; generated by OrcaSlicer 2.2.0\n; filament_colour = #FF5733\n; filament_diameter = 1.75\n;LAYER_CHANGE\nG1 X10 Y10 E1\n`;
    const meta = extractMetadata(gcode);
    expect(meta.color).toBe("#FF5733");
    expect(meta.diameter).toBe(1.75);
  });

  it("detects multi-material from tool changes", () => {
    const gcode = `; generated by OrcaSlicer 2.2.0\nT0\nG1 X10 E1\n;LAYER_CHANGE\nT1\nG1 X20 E2\nT2\nG1 X30 E3\n`;
    const meta = extractMetadata(gcode);
    expect(meta.isMultiMaterial).toBe(true);
    expect(meta.toolChangeCount).toBe(3);
  });

  it("does not flag single-tool as multi-material", () => {
    const gcode = `; generated by PrusaSlicer 2.7.1\nG28\nG1 X10 Y10 E1\n;LAYER_CHANGE\nG1 X20 Y20 E2\n`;
    const meta = extractMetadata(gcode);
    expect(meta.isMultiMaterial).toBe(false);
    expect(meta.toolChangeCount).toBe(0);
  });
});

// ─── SLICER_PROFILES structure ──────────────────────────

describe("SLICER_PROFILES", () => {
  it("has all required profiles", () => {
    const ids = Object.keys(SLICER_PROFILES);
    expect(ids).toContain("ankermaker");
    expect(ids).toContain("cura");
    expect(ids).toContain("prusaslicer");
    expect(ids).toContain("orcaslicer");
    expect(ids).toContain("bambustudio");
    expect(ids).toContain("simplify3d");
    expect(ids).toContain("superslicer");
    expect(ids).toContain("ideamaker");
    expect(ids).toContain("generic");
  });

  it("all profiles have required fields", () => {
    for (const [id, profile] of Object.entries(SLICER_PROFILES)) {
      expect(profile.id).toBe(id);
      expect(profile.name).toBeTruthy();
      expect(profile.layerMarker).toBeInstanceOf(RegExp);
      expect(profile.weightPatterns.length).toBeGreaterThan(0);
      expect(profile.pauseInstructions).toBeTruthy();
      expect(profile.pauseInstructions.title).toBeTruthy();
      expect(profile.pauseInstructions.steps.length).toBeGreaterThan(0);
      expect(profile.pauseInstructions.command).toBeTruthy();
    }
  });

  it("all layer markers are case-insensitive", () => {
    for (const profile of Object.values(SLICER_PROFILES)) {
      expect(profile.layerMarker.flags).toContain("i");
    }
  });
});
